
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalButtonUI;
import javax.swing.plaf.metal.MetalToggleButtonUI;
import javax.swing.table.JTableHeader;
import utilidades.EncabezadoTabla;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Elias-ZZZ
 */
public class Bambu_Soft extends javax.swing.JFrame {

    
    public Bambu_Soft() {
        UIManager.put("ToggleButton.select", Color.WHITE);
        UIManager.put("Button.select", Color.WHITE);
        initComponents();
        setVisible(true);
        setExtendedState(MAXIMIZED_BOTH);
        btnInicio.setSelected(true);
        btnInicio.setEnabled(false);
        JTableHeader header=TableCarrito.getTableHeader();
        header.setDefaultRenderer(new EncabezadoTabla());
        TableCarrito.setTableHeader(header);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelVentas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCarrito = new javax.swing.JTable();
        txtBarCode = new javax.swing.JTextField();
        txtArticle = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnAddToCart = new javax.swing.JButton();
        btnCash = new javax.swing.JToggleButton();
        btnCard = new javax.swing.JToggleButton();
        panelInicio = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JToggleButton();
        btnStats = new javax.swing.JToggleButton();
        btnInventario = new javax.swing.JToggleButton();
        btnEmpleados = new javax.swing.JToggleButton();
        btnAbout = new javax.swing.JToggleButton();
        btnInicio = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(3);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        panelVentas.setBackground(new java.awt.Color(255, 255, 255));
        panelVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pago");
        panelVentas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(81, 0, 126));
        panelVentas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 360, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pago del cliente");
        panelVentas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Articulo");
        panelVentas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Codigo de barras");
        panelVentas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Total: $");
        panelVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio");
        panelVentas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        txtPayment.setForeground(new java.awt.Color(0, 0, 0));
        txtPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        txtPayment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaymentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaymentFocusLost(evt);
            }
        });
        txtPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPaymentMouseExited(evt);
            }
        });
        panelVentas.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 340, 30));

        jSeparator5.setForeground(new java.awt.Color(81, 0, 126));
        panelVentas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 1120, 10));

        jSeparator6.setForeground(new java.awt.Color(81, 0, 126));
        panelVentas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 360, 10));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Carrito");
        panelVentas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Cantidad");
        panelVentas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(81, 0, 126));
        panelVentas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 730, 10));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Producto");
        panelVentas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        TableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Articulo", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCarrito.setGridColor(new java.awt.Color(140, 61, 168));
        TableCarrito.setSelectionBackground(new java.awt.Color(204, 204, 255));
        TableCarrito.getTableHeader().setReorderingAllowed(false);
        TableCarrito.getTableHeader().setBackground(new java.awt.Color(140,61,168));
        TableCarrito.getTableHeader().setBorder(BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1));
        jScrollPane1.setViewportView(TableCarrito);
        if (TableCarrito.getColumnModel().getColumnCount() > 0) {
            TableCarrito.getColumnModel().getColumn(0).setResizable(false);
            TableCarrito.getColumnModel().getColumn(1).setResizable(false);
            TableCarrito.getColumnModel().getColumn(2).setResizable(false);
            TableCarrito.getColumnModel().getColumn(3).setResizable(false);
        }

        panelVentas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 1100, 290));

        txtBarCode.setForeground(new java.awt.Color(0, 0, 0));
        txtBarCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        txtBarCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBarCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBarCodeFocusLost(evt);
            }
        });
        txtBarCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBarCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBarCodeMouseExited(evt);
            }
        });
        panelVentas.add(txtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 450, 30));

        txtArticle.setForeground(new java.awt.Color(0, 0, 0));
        txtArticle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        txtArticle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArticleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArticleFocusLost(evt);
            }
        });
        txtArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtArticleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtArticleMouseExited(evt);
            }
        });
        panelVentas.add(txtArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 30));

        txtPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPriceMouseExited(evt);
            }
        });
        panelVentas.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 210, 30));

        txtAmount.setForeground(new java.awt.Color(0, 0, 0));
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        txtAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountFocusLost(evt);
            }
        });
        txtAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAmountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAmountMouseExited(evt);
            }
        });
        panelVentas.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 210, 30));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Buscar");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        btnSearch.setFocusPainted(false);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSearchMouseReleased(evt);
            }
        });
        panelVentas.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 30));

        btnPagar.setBackground(new java.awt.Color(255, 255, 255));
        btnPagar.setForeground(new java.awt.Color(0, 0, 0));
        btnPagar.setText("Pagar");
        btnPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        btnPagar.setFocusPainted(false);
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPagarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPagarMouseReleased(evt);
            }
        });
        panelVentas.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 70, 30));

        btnAddToCart.setBackground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setForeground(new java.awt.Color(0, 0, 0));
        btnAddToCart.setText("Añadir al carrito");
        btnAddToCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        btnAddToCart.setFocusPainted(false);
        btnAddToCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddToCartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddToCartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddToCartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddToCartMouseReleased(evt);
            }
        });
        panelVentas.add(btnAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 30));

        btnCash.setBackground(new java.awt.Color(140, 61, 168));
        btnCash.setForeground(new java.awt.Color(255, 255, 255));
        btnCash.setText("Efectivo");
        btnCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        btnCash.setFocusPainted(false);
        btnCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCashMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCashMouseReleased(evt);
            }
        });
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });
        panelVentas.add(btnCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 130, 30));

        btnCard.setBackground(new java.awt.Color(140, 61, 168));
        btnCard.setForeground(new java.awt.Color(0, 0, 0));
        btnCard.setSelected(true);
        btnCard.setText("Tarjeta");
        btnCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 107, 168)));
        btnCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCardMouseReleased(evt);
            }
        });
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });
        panelVentas.add(btnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 130, 30));

        jPanel3.add(panelVentas, "card3");

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setLayout(null);

        jButton1.setText("jButton1");
        panelInicio.add(jButton1);
        jButton1.setBounds(200, 70, 130, 130);

        jSeparator1.setForeground(new java.awt.Color(81, 0, 126));
        panelInicio.add(jSeparator1);
        jSeparator1.setBounds(30, 470, 1110, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Producto agotado");
        panelInicio.add(jLabel3);
        jLabel3.setBounds(40, 430, 350, 32);

        jButton2.setText("jButton1");
        panelInicio.add(jButton2);
        jButton2.setBounds(360, 70, 130, 130);

        jButton3.setText("jButton1");
        panelInicio.add(jButton3);
        jButton3.setBounds(680, 70, 130, 130);

        jButton4.setText("jButton1");
        panelInicio.add(jButton4);
        jButton4.setBounds(40, 70, 130, 130);

        jButton5.setText("jButton1");
        panelInicio.add(jButton5);
        jButton5.setBounds(840, 70, 130, 130);

        jButton6.setText("jButton1");
        panelInicio.add(jButton6);
        jButton6.setBounds(1000, 70, 130, 130);

        jButton7.setText("jButton1");
        panelInicio.add(jButton7);
        jButton7.setBounds(520, 70, 130, 130);

        jSeparator2.setForeground(new java.awt.Color(81, 0, 126));
        panelInicio.add(jSeparator2);
        jSeparator2.setBounds(30, 50, 1110, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Lo más vendido");
        panelInicio.add(jLabel4);
        jLabel4.setBounds(40, 10, 184, 32);

        jButton8.setText("jButton1");
        panelInicio.add(jButton8);
        jButton8.setBounds(40, 280, 130, 130);

        jButton9.setText("jButton1");
        panelInicio.add(jButton9);
        jButton9.setBounds(200, 280, 130, 130);

        jButton10.setText("jButton1");
        panelInicio.add(jButton10);
        jButton10.setBounds(360, 280, 130, 130);

        jButton11.setText("jButton1");
        panelInicio.add(jButton11);
        jButton11.setBounds(520, 280, 130, 130);

        jButton12.setText("jButton1");
        panelInicio.add(jButton12);
        jButton12.setBounds(680, 280, 130, 130);

        jButton13.setText("jButton1");
        panelInicio.add(jButton13);
        jButton13.setBounds(840, 280, 130, 130);

        jButton14.setText("jButton1");
        panelInicio.add(jButton14);
        jButton14.setBounds(1000, 280, 130, 130);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Producto a punto de agotarse");
        panelInicio.add(jLabel5);
        jLabel5.setBounds(40, 220, 350, 32);

        jSeparator3.setForeground(new java.awt.Color(81, 0, 126));
        panelInicio.add(jSeparator3);
        jSeparator3.setBounds(30, 260, 1110, 40);

        jButton15.setText("jButton1");
        panelInicio.add(jButton15);
        jButton15.setBounds(40, 490, 130, 130);

        jButton16.setText("jButton1");
        panelInicio.add(jButton16);
        jButton16.setBounds(200, 490, 130, 130);

        jButton17.setText("jButton1");
        panelInicio.add(jButton17);
        jButton17.setBounds(360, 490, 130, 130);

        jButton18.setText("jButton1");
        panelInicio.add(jButton18);
        jButton18.setBounds(520, 490, 130, 130);

        jButton19.setText("jButton1");
        panelInicio.add(jButton19);
        jButton19.setBounds(680, 490, 130, 130);

        jButton20.setText("jButton1");
        panelInicio.add(jButton20);
        jButton20.setBounds(840, 490, 130, 130);

        jButton21.setText("jButton1");
        panelInicio.add(jButton21);
        jButton21.setBounds(1000, 490, 130, 130);

        jPanel3.add(panelInicio, "card2");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 1180, 750));

        jPanel1.setBackground(new java.awt.Color(140, 61, 168));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        btnLogout.setBackground(new java.awt.Color(102, 0, 102));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Cerrar sesión");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogout.setBorderPainted(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setOpaque(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 30, 100, 30));

        Image logo=new ImageIcon(getClass().getResource("/img/logo.jpg")).getImage();
        logo=logo.getScaledInstance(183,60,java.awt.Image.SCALE_SMOOTH);
        ImageIcon logo2=new ImageIcon(logo);
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(logo2);
        jLabel1.setText("LOGO");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 1560, 60));

        jPanel2.setBackground(new java.awt.Color(28, 177, 217));
        jPanel2.setLayout(null);

        btnVentas.setBackground(new java.awt.Color(0, 0, 0));
        btnVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.setHorizontalAlignment(SwingConstants.LEFT);
        btnVentas.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
            BorderFactory.createEmptyBorder(15,15,15,15)));
    btnVentas.setBorderPainted(false);
    btnVentas.setFocusPainted(false);
    btnVentas.setFocusable(false);
    btnVentas.setOpaque(false);
    btnVentas.setRequestFocusEnabled(false);
    btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnVentasMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            btnVentasMouseExited(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            btnVentasMousePressed(evt);
        }
    });
    btnVentas.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVentasActionPerformed(evt);
        }
    });
    jPanel2.add(btnVentas);
    btnVentas.setBounds(0, 90, 190, 90);

    btnStats.setBackground(new java.awt.Color(0, 0, 0));
    btnStats.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    btnStats.setForeground(new java.awt.Color(255, 255, 255));
    btnStats.setText("Estadisticas");
    btnStats.setHorizontalAlignment(SwingConstants.LEFT);
    btnStats.setActionCommand("");
    btnStats.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
        BorderFactory.createEmptyBorder(15,15,15,15)));
btnStats.setBorderPainted(false);
btnStats.setFocusPainted(false);
btnStats.setFocusable(false);
btnStats.setOpaque(false);
btnStats.setRequestFocusEnabled(false);
btnStats.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnStatsMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnStatsMouseExited(evt);
    }
    public void mousePressed(java.awt.event.MouseEvent evt) {
        btnStatsMousePressed(evt);
    }
    });
    btnStats.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnStatsActionPerformed(evt);
        }
    });
    jPanel2.add(btnStats);
    btnStats.setBounds(0, 180, 190, 90);

    btnInventario.setBackground(new java.awt.Color(0, 0, 0));
    btnInventario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    btnInventario.setForeground(new java.awt.Color(255, 255, 255));
    btnInventario.setText("Inventario");
    btnInventario.setHorizontalAlignment(SwingConstants.LEFT);
    btnInventario.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
        BorderFactory.createEmptyBorder(15,15,15,15)));
btnInventario.setBorderPainted(false);
btnInventario.setFocusPainted(false);
btnInventario.setFocusable(false);
btnInventario.setOpaque(false);
btnInventario.setRequestFocusEnabled(false);
btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnInventarioMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnInventarioMouseExited(evt);
    }
    public void mousePressed(java.awt.event.MouseEvent evt) {
        btnInventarioMousePressed(evt);
    }
    });
    btnInventario.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnInventarioActionPerformed(evt);
        }
    });
    jPanel2.add(btnInventario);
    btnInventario.setBounds(0, 270, 190, 90);

    btnEmpleados.setBackground(new java.awt.Color(0, 0, 0));
    btnEmpleados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
    btnEmpleados.setText("Empleados");
    btnEmpleados.setHorizontalAlignment(SwingConstants.LEFT);
    btnEmpleados.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
        BorderFactory.createEmptyBorder(15,15,15,15)));
btnEmpleados.setBorderPainted(false);
btnEmpleados.setFocusPainted(false);
btnEmpleados.setFocusable(false);
btnEmpleados.setOpaque(false);
btnEmpleados.setRequestFocusEnabled(false);
btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnEmpleadosMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnEmpleadosMouseExited(evt);
    }
    public void mousePressed(java.awt.event.MouseEvent evt) {
        btnEmpleadosMousePressed(evt);
    }
    });
    btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEmpleadosActionPerformed(evt);
        }
    });
    jPanel2.add(btnEmpleados);
    btnEmpleados.setBounds(0, 360, 190, 90);

    btnAbout.setBackground(new java.awt.Color(0, 0, 0));
    btnAbout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    btnAbout.setForeground(new java.awt.Color(255, 255, 255));
    btnAbout.setText("Acerca de");
    btnAbout.setHorizontalAlignment(SwingConstants.LEFT);
    btnAbout.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
        BorderFactory.createEmptyBorder(15,15,15,15)));
btnAbout.setBorderPainted(false);
btnAbout.setFocusPainted(false);
btnAbout.setFocusable(false);
btnAbout.setOpaque(false);
btnAbout.setRequestFocusEnabled(false);
btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnAboutMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnAboutMouseExited(evt);
    }
    public void mousePressed(java.awt.event.MouseEvent evt) {
        btnAboutMousePressed(evt);
    }
    });
    btnAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAboutActionPerformed(evt);
        }
    });
    jPanel2.add(btnAbout);
    btnAbout.setBounds(0, 560, 190, 90);

    btnInicio.setBackground(new java.awt.Color(0, 0, 0));
    btnInicio.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    btnInicio.setForeground(new java.awt.Color(255, 255, 255));
    btnInicio.setText("Inicio");
    btnInicio.setHorizontalAlignment(SwingConstants.LEFT);
    btnInicio.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 1),
        BorderFactory.createEmptyBorder(15,15,15,15)));
btnInicio.setBorderPainted(false);
btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
btnInicio.setFocusPainted(false);
btnInicio.setFocusable(false);
btnInicio.setOpaque(false);
btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnInicioMouseClicked(evt);
    }
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        btnInicioMouseEntered(evt);
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        btnInicioMouseExited(evt);
    }
    public void mousePressed(java.awt.event.MouseEvent evt) {
        btnInicioMousePressed(evt);
    }
    });
    btnInicio.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnInicioActionPerformed(evt);
        }
    });
    jPanel2.add(btnInicio);
    btnInicio.setBounds(0, 0, 190, 90);

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 680));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        changeButtons("Empleados");
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseEntered
        btnEmpleados.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnEmpleadosMouseEntered

    private void btnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseExited
        btnEmpleados.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnEmpleadosMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        btnInicio.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        btnInicio.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        changeButtons("Inicio");
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        btnInventario.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        btnInventario.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        changeButtons("Inventario");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        btnVentas.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        btnVentas.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        changeButtons("Ventas");
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnStatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseEntered
        btnStats.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnStatsMouseEntered

    private void btnStatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMouseExited
        btnStats.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnStatsMouseExited

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
        changeButtons("Stats");
    }//GEN-LAST:event_btnStatsActionPerformed

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        changeButtons("About");
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        
        
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setBorderPainted(true);
        repaint();
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setBorderPainted(false);
        repaint();
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed
        btnInicio.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnInicioMousePressed

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        btnVentas.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnVentasMousePressed

    private void btnStatsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatsMousePressed
        btnStats.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnStatsMousePressed

    private void btnInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMousePressed
        btnInventario.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnInventarioMousePressed

    private void btnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMousePressed
        btnEmpleados.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnEmpleadosMousePressed

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        btnAbout.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        btnLogout.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnLogoutMousePressed

    private void txtPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPaymentMouseEntered
        txtPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtPaymentMouseEntered

    private void txtPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPaymentMouseExited
        if(!(txtPayment.isFocusOwner()))
            txtPayment.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtPaymentMouseExited

    private void txtPaymentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaymentFocusGained
        txtPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtPaymentFocusGained

    private void txtPaymentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaymentFocusLost
        txtPayment.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtPaymentFocusLost

    private void txtBarCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarCodeFocusGained
        txtBarCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtBarCodeFocusGained

    private void txtBarCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarCodeFocusLost
        txtBarCode.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtBarCodeFocusLost

    private void txtBarCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarCodeMouseEntered
        txtBarCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtBarCodeMouseEntered

    private void txtBarCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarCodeMouseExited
        if(!(txtBarCode.isFocusOwner()))
            txtBarCode.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtBarCodeMouseExited

    private void txtArticleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticleFocusGained
        txtArticle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtArticleFocusGained

    private void txtArticleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArticleFocusLost
        txtArticle.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtArticleFocusLost

    private void txtArticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArticleMouseEntered
        txtArticle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtArticleMouseEntered

    private void txtArticleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArticleMouseExited
        if(!(txtArticle.isFocusOwner()))
            txtArticle.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtArticleMouseExited

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        txtPrice.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPriceMouseEntered
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtPriceMouseEntered

    private void txtPriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPriceMouseExited
        if(!(txtPrice.isFocusOwner()))
            txtPrice.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtPriceMouseExited

    private void txtAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusGained
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtAmountFocusGained

    private void txtAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusLost
        txtAmount.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtAmountFocusLost

    private void txtAmountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmountMouseEntered
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_txtAmountMouseEntered

    private void txtAmountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmountMouseExited
        if(!(txtAmount.isFocusOwner()))
            txtAmount.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_txtAmountMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        btnSearch.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 11));
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),3));
    }//GEN-LAST:event_btnSearchMousePressed

    private void btnSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseReleased
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 12));
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnSearchMouseReleased

    private void btnPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseEntered
        btnPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnPagarMouseEntered

    private void btnPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseExited
        btnPagar.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_btnPagarMouseExited

    private void btnPagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMousePressed
        btnPagar.setFont(new java.awt.Font("Dialog", 1, 11));
        btnPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),3));
    }//GEN-LAST:event_btnPagarMousePressed

    private void btnPagarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseReleased
        btnPagar.setFont(new java.awt.Font("Dialog", 1, 12));
        btnPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnPagarMouseReleased

    private void btnAddToCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMouseEntered
        btnAddToCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnAddToCartMouseEntered

    private void btnAddToCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMouseExited
        btnAddToCart.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_btnAddToCartMouseExited

    private void btnAddToCartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMousePressed
        btnAddToCart.setFont(new java.awt.Font("Dialog", 1, 11));
        btnAddToCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),3));
    }//GEN-LAST:event_btnAddToCartMousePressed

    private void btnAddToCartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMouseReleased
        btnAddToCart.setFont(new java.awt.Font("Dialog", 1, 12));
        btnAddToCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnAddToCartMouseReleased

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        if(btnCard.isSelected()){
            btnCard.setSelected(false);
        }
        else{
            btnCard.setSelected(true);
        }
        if(btnCash.isSelected()){
            btnCard.setForeground(Color.WHITE);
            btnCash.setForeground(Color.BLACK);
        }
        else{
            btnCard.setForeground(Color.BLACK);
            btnCash.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        if(btnCash.isSelected()){
            btnCash.setSelected(false);
            //btnCash.setForeground(Color.WHITE);
        }
        else{
            btnCash.setSelected(true);
            //btnCash.setForeground(Color.BLACK);
        }
        if(btnCard.isSelected()){
            btnCard.setForeground(Color.BLACK);
            btnCash.setForeground(Color.WHITE);
        }
        else{
            btnCard.setForeground(Color.WHITE);
            btnCash.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnCardActionPerformed

    private void btnCashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashMouseEntered
        btnCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnCashMouseEntered

    private void btnCashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashMouseExited
        btnCash.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_btnCashMouseExited

    private void btnCashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashMousePressed
        btnCash.setFont(new java.awt.Font("Dialog", 1, 11));
        btnCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),3));
        if(!btnCash.isSelected())
            btnCash.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCashMousePressed

    private void btnCashMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashMouseReleased
        btnCash.setFont(new java.awt.Font("Dialog", 1, 12));
        btnCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnCashMouseReleased

    private void btnCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardMouseEntered
        btnCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnCardMouseEntered

    private void btnCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardMouseExited
        btnCard.setBorder(BorderFactory.createLineBorder(new java.awt.Color(152,107,168)));
    }//GEN-LAST:event_btnCardMouseExited

    private void btnCardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardMousePressed
        btnCard.setFont(new java.awt.Font("Dialog", 1, 11));
        btnCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),3));
        if(!btnCard.isSelected())
            btnCard.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCardMousePressed

    private void btnCardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCardMouseReleased
        btnCard.setFont(new java.awt.Font("Dialog", 1, 12));
        btnCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(140, 61, 168),2));
    }//GEN-LAST:event_btnCardMouseReleased
    private void changeButtons(String s){
        setButtonsNormal();
        switch(s){
            case "Inicio":
                btnInicio.setEnabled(false);
                //btnInicio.setDisabledTextColor(new java.awt.Color(0,0,0));
                btnInicio.setSelected(true);
                break;
            case "Empleados":
                btnEmpleados.setForeground(new java.awt.Color(0,0,0));
                btnEmpleados.setEnabled(false);
                btnEmpleados.setSelected(true);
                break;
            case "About":
                btnAbout.setEnabled(false);
                btnAbout.setForeground(new java.awt.Color(0,0,0));
                btnAbout.setSelected(true);
                break;
            case "Inventario":
                btnInventario.setEnabled(false);
                btnInventario.setForeground(new java.awt.Color(0,0,0));
                btnInventario.setSelected(true);
                break;
            case "Stats":
                btnStats.setEnabled(false);
                btnStats.setForeground(new java.awt.Color(0,0,0));
                btnStats.setSelected(true);
                break;
            case "Ventas":
                btnVentas.setEnabled(false);
                btnVentas.setForeground(new java.awt.Color(0,0,0));
                btnVentas.setSelected(true);
                break;
        }
        repaint();
    }
    private void setButtonsNormal(){
        btnEmpleados.setForeground(new java.awt.Color(255,255,255));
        btnEmpleados.setEnabled(true);
        btnEmpleados.setSelected(false);
        btnInicio.setEnabled(true);
        btnInicio.setForeground(new java.awt.Color(255,255,255));
        btnInicio.setSelected(false);
        btnAbout.setEnabled(true);
        btnAbout.setForeground(new java.awt.Color(255,255,255));
        btnAbout.setSelected(false);
        btnInventario.setEnabled(true);
        btnInventario.setForeground(new java.awt.Color(255,255,255));
        btnInventario.setSelected(false);
        btnStats.setEnabled(true);
        btnStats.setForeground(new java.awt.Color(255,255,255));
        btnStats.setSelected(false);
        btnVentas.setEnabled(true);
        btnVentas.setForeground(new java.awt.Color(255,255,255));
        btnVentas.setSelected(false);
        repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bambu_Soft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bambu_Soft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bambu_Soft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bambu_Soft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bambu_Soft().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCarrito;
    private javax.swing.JToggleButton btnAbout;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JToggleButton btnCard;
    private javax.swing.JToggleButton btnCash;
    private javax.swing.JToggleButton btnEmpleados;
    private javax.swing.JToggleButton btnInicio;
    private javax.swing.JToggleButton btnInventario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JToggleButton btnStats;
    private javax.swing.JToggleButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtArticle;
    private javax.swing.JTextField txtBarCode;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
